kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: cloud-paas
  labels:
    app: redis
spec:
  ports:
    - name: tcp-6379
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: NodePort
