apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage
  namespace: cloud-paas
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-share
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  phase: Bound
