---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-storage
  namespace: cloud-paas
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-share
